### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by Relrin** [coddingtonbear/django-neighborhoods#1]
Im working with Django 1.8.2 and taken this `AttributeError` exception, when try to get data for CA neighborhoods:

```
root@28025a5bdb3e:/code/civic# python manage.py import_neighborhoods CA
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/code/civic/location/management/commands/import_neighborhoods.py", line 11, in <module>
    from neighborhoods.importer import NeighborhoodShapefileImporter, \
  File "/usr/local/lib/python2.7/dist-packages/neighborhoods/importer.py", line 17, in <module>
    class NeighborhoodShapefileImporter(object):
  File "/usr/local/lib/python2.7/dist-packages/neighborhoods/importer.py", line 21, in NeighborhoodShapefileImporter
    @transaction.commit_on_success
AttributeError: 'module' object has no attribute 'commit_on_success'
```

We can avoid this situation, when use `@transaction.atomic` instead of `@transaction.commit_on_success` on 22 line of `django-neighborhoods/neighborhoods/importer.py file`

**Comment by coddingtonbear** [comment]
Awesome!  Thanks for the heads-up.  Would you mind posting a pull request with that change?
